function hamburguesa() {
    var menu = document.getElementById('nav-botones')

    if (menu.style.display == 'block') {    // Esto es = Si la etiqueta "menu" que tiene "style", tiene display en "block", quiero que lo cambie a "display:none"
        menu.style.display = 'none'
    }
    else {
        menu.style.display = 'block'
    }
}

/*BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB*/
/*BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB*/

function MisterMouseOver() {
    var MisterMouseOver = document.getElementById('img-der-sec2')
    MisterMouseOver.style.backgroundImage = 'url(imagenes/ka-interior-1-dirt.jpg)'
}

function MisterMouseOut() {
    var MisterMouseOut = document.getElementById('img-der-sec2')
    MisterMouseOut.style.backgroundImage = 'url(imagenes/ka-interior-1-clean.jpg)'
}

/*BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB*/
/*BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB*/

function MOverSec2CajaIzq() {
    var MOverSec2CajaIzq = document.getElementById('sec2-cajaizq')
    MOverSec2CajaIzq.style.backgroundImage = 'url(imagenes/ka-interior-2-dirt.jpg)'
}

function MOutSec2CajaIzq() {
    var MOutSec2CajaIzq = document.getElementById('sec2-cajaizq')
    MOutSec2CajaIzq.style.backgroundImage = 'url(imagenes/ka-interior-2-clean.jpg)'
}

/*BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB*/
/*BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB*/

function MOverSec2CajaDer() {
    var MOverSec2CajaDer = document.getElementById('sec2-cajader')
    MOverSec2CajaDer.style.backgroundImage = 'url(imagenes/ka-interior-3-dirt.jpg)'
}

function MOutSec2CajaDer() {
    var MOutSec2CajaDer = document.getElementById('sec2-cajader')
    MOutSec2CajaDer.style.backgroundImage = 'url(imagenes/ka-interior-3-clean.jpg)'
}

/*BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB*/
/*BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB*/